name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: Swatinem/rust-cache@v2
    - name: Install Just
      run: cargo install just
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache register
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: crypt
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max`
    - name: Run test
      run: just test
